version: '3'

services:
  web:
    build: .
    command: sh -c "uvicorn main:app --reload --host=0.0.0.0 --port=8000"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    restart: on-failure