services:
  web:
    build: ./app
    command: sh -c "uvicorn main:app --reload --host=0.0.0.0 --port=8000"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    restart: on-failure
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: satlab
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
    driver: local
